/*
	SCRIPT SQL PARA CRIAÇÃO
	DA TABELA DE CLIENTES
*/

CREATE TABLE Client(
	ID UNIQUEIDENTIFIER PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL,
	EMAIL NVARCHAR(100) NOT NULL UNIQUE,
	BIRTHDATE DATE NOT NULL);


-- CADASTRO CLIENTE
INSERT INTO Client (ID, NAME, EMAIL, BIRTHDATE)
	VALUES
		(NEWID(), 'Ana Maria', 'anamaria@gmail.com', '2000-12-01'),
		(NEWID(), 'João Pedro', 'joaopedro@gmail.com', '2000-10-04');

-- CONSULTA CLIENTE
SELECT ID, NAME, EMAIL, BIRTHDATE
FROM CLIENT
ORDER BY NAME;